### ISSUE TITLE
Deadlock on "Searching 0.0%"

### ISSUE THREAD

**Issue by yuchdev** [samuel-cavalcanti/DuckDuckGo-Image-Search-API#1]
The searching process is being frozen at 0.0%, downloading for 100 photos. I was waiting 40 minutes before the keyboard interrupt.

**Comment by samuel-cavalcanti** [comment]
My "API" actually is some kind a hack on duckduckgo, my last commit have 2 years old.
__Is not official API__ Sorry if I confuse you  😞 

Please consult the oficial API :
https://duckduckgo.com/api
